### ISSUE TITLE
README and DISCLAIMER links 404

### ISSUE THREAD

**Issue by mxmilkiib** [boytwink/diyhrt#1]
Currently they are
- [readme](https://codeberg.org/diyhrt/pages/blob/main/README.md)
- [disclaimer](https://codeberg.org/diyhrt/pages/blob/main/DISCLAIMER.md)

P.S. do you care about having two issue queues, one here or on Codeberg? Or should I use Codeberg in future?

**Comment by soapingtime** [comment]
fixed, thanks! I don't mind having issues on codeberg, but I check github more often and the 404 sends you to github because I figure more people have an account there
